config/routes.rb
Rails.application.routes.draw do
  
  get 'takers/new'

  resources :quizzes do
    resources :takers #this probably shouldnt be nested, so that the taker can take any quiz...mabye. i dunno
    resources :characters
    
    
    resources :questions do   
      resources :answers
    end
  end
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question, inverse_of: :answers
  belongs_to :character, inverse_of: :answers
end

app/models/character.rb
class Character < ActiveRecord::Base
	has_many :answers, inverse_of: :character 
	belongs_to :quiz, inverse_of: :characters
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, inverse_of: :question 

	belongs_to :quiz, inverse_of: :questions

	accepts_nested_attributes_for :answers

	delegate :text, to: :answer, prefix: true, allow_nil: true 
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :questions, inverse_of: :quiz 
	has_many :characters, inverse_of: :quiz
	has_many :takers, inverse_of: :quiz
end

app/models/taker.rb
class Taker < ActiveRecord::Base
  belongs_to :quiz, inverse_of: :takers
  has_many :questions, :through => :quiz
  has_many :answers, :through => :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_filter :load_question

	def index
		@answers = @question.answers
	end

	private
	def load_question
		@question = Question.find(question_id)
	end

	def question_id
		params[:question_id]
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	before_filter :load_quiz

	def index
		@characters = @quiz.characters
	end

	def new
		@character = Character.new
	end

	def create
		@character = @quiz.characters.build(character_params)
		@character.quiz_id = quiz_id

		if @character.save
			redirect_to quiz_characters_path(@quiz), flash: {success: "Created Character"}
		else
			flash.now[:error] = @character.errors.full_messages
		end
	end

	def show
	end

	private
	def character_params
		params.require(:character).permit(:name)
	end

	def quiz_id
		params[:quiz_id]
	end

	def load_quiz
		@quiz = Quiz.find(quiz_id)
	end
end	

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :load_question, except: [:index, :new, :create, :tie_breaker]
  before_filter :load_characters, only: [:new, :edit]
  before_filter :load_quiz

  def index
  	@questions = @quiz.questions
  end

  def new
    @tie_breaker = nil

    if params[:link] == 'tie_breaker'  
      @tie_breaker = true
    end
    
    @question = Question.new 
    
    @answer = @question.answers.build
  end

  def tie_breaker
    @question = Question.new 
    
    @answer = @question.answers.build
  end

  def create
    @question = @quiz.questions.build(question_params)
    @question.quiz_id = quiz_id
    
    if @question.save && @question.tie_breaker
      redirect_to quiz_questions_path(@quiz), flash: {success: 'Created Tie-Breaker Question'}
    elsif @question.save && !@question.tie_breaker
      redirect_to quiz_questions_path(@quiz), flash: {success: 'Created Question'}
    else
      flash.now[:error] = @question.errors.full_messages
    end
  end

  def show
  end

  def edit   
   
  end

  def update
    successful_update = 'Updated Tie-Breaker Question and Answers' if @question.tie_breaker
    successful_update = 'Updated Question and Answers' if !@question.tie_breaker


    if @question.update_attributes(question_params)
      
      redirect_to quiz_questions_url(@quiz), flash: {success: successful_update}
    else
      flash.now[:error] = @question.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash = {flash: {success: 'Deleted Question'}}
    else
      flash = {flash: {error: @question.errors.full_messages}}
    end

    redirect_to quiz_questions_url(@quiz, @question), flash
  end
  
  private
  def load_characters
    load_quiz
    @characters = @quiz.characters
  end

  def load_question
    @question = Question.find(question_id)
  end

  def question_id
    params[:id]
  end

  def question_params
    params.require(:question).permit(:text, :tie_breaker,
                                      answers_attributes: [:id, :text, :character_id])
  end

  def quiz_id
    params[:quiz_id]
  end

  def load_quiz
    @quiz = Quiz.find(quiz_id)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
	before_filter :load_quiz, except: [:index, :new, :create]
	before_filter :load_characters, only: [:show]
	before_filter :load_questions, only: [:show]

	def index
		@quizzes = Quiz.all
	end

	def new
		@quiz = Quiz.new
	end

	def create
		@quiz = Quiz.new(quiz_params)
		
		if @quiz.save
			redirect_to quizzes_path, flash: {success: "Created Quiz"}
		else
			flash.now[:error] = @quiz.errors.full_messages
		end
	end

	def edit
	end 

	def update
    if @quiz.update_attributes(quiz_params)
      redirect_to quizzes_url(@quiz), flash: {success: "Updated Quiz"}
    else
      flash.now[:error] = @quiz.errors.full_messages
      render :edit
    end
  end

	def show
		@tie_breaker = @quiz.questions.find_by(tie_breaker: true)
	end

	private
	def load_questions
		@questions = @quiz.questions
	end

	def load_characters
		@characters = @quiz.characters
	end

	def load_quiz
    @quiz = Quiz.find(quiz_id)
  end

  def quiz_id
    params[:id]
  end

	def quiz_params
		params.require(:quiz).permit(:name)
	end
end	

app/controllers/takers_controller.rb
class TakersController < ApplicationController
  before_filter :load_quiz
  before_filter :load_questions
  before_filter :load_characters  

  def new
  	@taker = Taker.new    
  end
  
  def create
    # hey = params[:answer_1]
    
     character_answers_tally = []
     character_array = []
     index = 0
     @characters.each do |character|
       character_array.push(character.id)   
       #character_key[character_"index".to_sym] = character.id
       character_answers_tally.push(0)
     end 


    # #make function that takes hash name
    # params.each do |answer, value|
    #   answer = Answer.find(value)
    #   character = answer.character
    #   character_index = character.id - 1
      
    #   character_answers_tally[character_index] += 1
    # end
    answer_number = 0
    @questions.size.times do
      answer_number += 1
      answer_id = params["answer_#{answer_number}".to_sym]
      answer = Answer.find(answer_id)
      character = answer.character
      character_index = character_array.index(character.id)
      character_answers_tally[character_index] += 1
    end

    max_answers = character_answers_tally.max 
    index_of_max = character_answers_tally.index(max_answers)

    if character_answers_tally.count(max_answers) == 1 
      
      redirect_to '#' #this should be going to the static page for showing your character
    else
      redirect_to '#' #the tie breaker question
    end
    
    redirect_to quiz_questions_path(@quiz), flash: {success: character_answers_tally}
  end

  
  private
  def load_characters
    load_quiz
    @characters = @quiz.characters
  end

  def load_questions
    load_quiz
    @questions = @quiz.questions.select { |question| question.tie_breaker.nil?} #have to get ones where they arnt new
  end

  def load_quiz
		@quiz = Quiz.find(quiz_id)
	end

	def quiz_id
		params[:quiz_id]
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/takers_helper.rb
module TakersHelper
end

app/views/answers/index.html.erb
<%= @question.text %>
<% @answers.each do |answer| %>
	<p><%= answer.text %></p>
<% end %>

app/views/characters/index.html.erb
<h1>Characters</h1>

<%= link_to 'New Character', new_quiz_character_path(@quiz) %>
<%= link_to 'Questions', quiz_questions_path(@quiz) %>

<%= @characters.each do |character|%>
	<p><%= character.name %></p>
<% end %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= form_for [@quiz, @character] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |message_type, message|%>
		<div class="alert alert-<%= message_type%>"><%= message%></div>
	<% end %>
	<%= yield %>

</body>
</html>

app/views/questions/_form_fields.erb
<%= f.fields_for :answers, @answer do |builder| %>	
	<%= builder.label :text, "Answer for #{character.name} " %>
	<%= builder.text_area :text %>
	<%= builder.hidden_field :character_id, value: character.id %>
<% end %>	

app/views/questions/delete.html.erb
<h1>Questions#delete</h1>
<p>Find me in app/views/questions/delete.html.erb</p>

app/views/questions/edit.html.erb
<% header_title = 'Edit Tie-Breaker Question' if @question.tie_breaker %>	
<% header_title = 'Edit Question' if !@question.tie_breaker %>
<% question_label = 'Your Tie-Breaker Question' if @question.tie_breaker %>	
<% question_label = 'Your Question' if !@question.tie_breaker %>	


<h1><%= header_title %></h1>
<p>Find me in app/views/questions/edit.html.erb</p>

<%= form_for [@quiz, @question] do |f| %>
	<%= f.label :text, question_label %>
	<%= f.text_area :text%>
		<% @characters.each do |character| %>
			<p>
				<%= render 'form_fields', f: f, character: character %>
			</p>
		<% end %>		

	<%= f.submit 'Update' %>
<% end %>

app/views/questions/index.html.erb
<h1><%= @quiz.name %></h1>

<%= link_to "Characters", quiz_characters_path(@quiz) %>
<%= link_to 'New Question', new_quiz_question_path(@quiz) %>

<% if @questions.any? %>
	<% @questions.each do |question| %>
		<h3><%= 'Tie Breaker' if question.tie_breaker %></h3>
		<p><%=question.text%></p>
		<%= link_to 'Edit Question', edit_quiz_question_path(@quiz, question)%>
		<%= link_to 'Show Answers', quiz_question_answers_path(@quiz, question)%>
		<%=link_to "Delete", quiz_question_path(@quiz, question.id), :method => :delete, :class => "delete"%>  
	<% end %>
<% else %>
	<p>There are no questions yet.</p>
<% end %>	

app/views/questions/new.html.erb
<% question_label = 'Your Tie-Breaker Question' if @tie_breaker %>	
<% question_label = 'Your New Question' if !@tie_breaker %>	
<% header_title = 'New Tie-Breaker Question' if @tie_breaker %>	
<% header_title = 'New Question' if !@tie_breaker %>	


<h1><%= header_title %></h1>

<%= form_for [@quiz, @question] do |f| %>	
	<%= f.label :text, question_label %>
	
	<%= f.text_area :text%>
		<% @characters.each do |character| %>
		<%= (f.hidden_field :tie_breaker, value: true) if @tie_breaker %>	
			<p>
				<%= render 'form_fields', f: f, character: character %>	  	
			</p>
		<% end %>		
	<%= f.submit%>
<% end %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/quizzes/edit.html.erb
<h1>Edit Quiz</h1>
<p>Find me in app/views/questions/new.html.erb</p>

<%= form_for @quiz do |f| %>
	<%= f.label :name, "Quiz Name" %>
	<%= f.text_field :name%>

	<%= f.submit%>
<% end %>

app/views/quizzes/index.html.erb
<%= link_to 'New Quiz', new_quiz_path %>

<% @quizzes.each do |quiz| %>
	<p><%=quiz.name%></p>
	<%= link_to 'Show quiz', quiz_path(quiz)%>
	<%= link_to 'Edit quiz', edit_quiz_path(quiz)%>
	  
<% end %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>
<p>Find me in app/views/questions/new.html.erb</p>

<%= form_for @quiz do |f| %>
	<%= f.label :name, "Name of the Quiz" %>
	<%= f.text_field :name%>

	<%= f.submit%>
<% end %>

app/views/quizzes/show.html.erb
<h1><%= @quiz.name %></h1>

<h3>Characters</h3>
<%= link_to 'Create New Character', new_quiz_character_path(@quiz) %>

<% if @characters.any?  %>
	<% @characters.each do |character|%>
		<p><%= character.name%></p>
	<% end %>
<% else %>
	<p>There are no characters yet. <%= link_to 'Create Some', new_quiz_character_path(@quiz) %></p>
<% end %>

<h3>Questions</h3>
<%= link_to 'Create New Question', new_quiz_question_path(@quiz) %>

<% if @questions.any?  %>
	<% @questions.each do |question|%>
		<h3><%= 'Tie Breaker' if question.tie_breaker %></h3>
		<p><%= question.text %></p>
		<%= link_to 'Edit Question', edit_quiz_question_path(@quiz, question, link: 'tie_breaker') %>
		<%= link_to 'Show Answers', quiz_question_answers_path(@quiz, question, question.answers) %>
	<% end %>
<% else %>
	<p>There are no questions yet. <%= link_to 'Create Some', new_quiz_question_path(@quiz) %></p>
<% end %>
<% unless @tie_breaker%>
	<%= link_to 'Create New Tie-Breaker Question', new_quiz_question_path(@quiz, link: 'tie_breaker' ) %>
<% end %>	

app/views/takers/new.html.erb
<% section_index = 0 %>
<h1>Begin</h1>
<p>Fill out the most appropriate answer for each question</p>

<%= form_tag(quiz_takers_path(@quiz, method: 'post')) do  %>
<!-- <form action=<%= quiz_takers_path(@quiz) %> method="post"> -->
	<% @questions.each do |question| %>
		<% section_index += 1 %>

		<div class='taker_question', id=<%="question_#{section_index}"%> >
		<p><%= question.text %></p>
	
		<% question.answers.each_with_index do |answer, index| %>
			
			<%= radio_button_tag("answer_#{index + 1}".to_sym, answer.id) %>	<%= answer.text %>
		<!--	<input type="radio" name=<%= "answer_#{index + 1}" %> value=<%= answer.id %>><%= answer.text %> -->
		<% end %>
		</div>
	<% end %>
	<%= submit_tag 'Submit' %>
<% end %>